# Generated by Django 5.0.7 on 2024-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_deck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
