# Generated by Django 5.0.7 on 2024-07-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_deck_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='collecter_number',
            new_name='collector_number',
        ),
    ]
