# Generated by Django 5.0.7 on 2024-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_collecter_number_deck_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck',
            field=models.TextField(default=''),
        ),
    ]
