# Generated by Django 5.0.7 on 2024-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_deck_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='allow_duplicate_basic_lands',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='only_full_art_lands',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='random_basic_lands',
            field=models.BooleanField(default=True),
        ),
    ]
