# Generated by Django 5.0.7 on 2024-07-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_deck_allow_duplicate_basic_lands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
