# Generated by Django 5.0.7 on 2024-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_deck_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='allow_duplicate_basic_lands',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='only_full_art_lands',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='random_basic_lands',
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
