# Generated by Django 5.0.7 on 2024-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_deck_allow_duplicate_basic_lands_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_basic_lands', models.BooleanField()),
                ('only_full_art_lands', models.BooleanField()),
                ('allow_duplicate_basic_lands', models.BooleanField()),
            ],
        ),
    ]
