# Generated by Django 5.0.7 on 2024-07-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='params',
            old_name='random_basic_lands',
            new_name='random_basic_land_art',
        ),
    ]
