# Generated by Django 5.0.7 on 2024-07-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_rename_only_full_art_lands_params_only_full_art_basi_lands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='params',
            old_name='only_full_art_basi_lands',
            new_name='only_full_art_basic_lands',
        ),
    ]
